AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails:
  Enabled: true

StringLiterals:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
