# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea01cbc820195d4acc9fbae53973f93824ebdcad185ee699abd2defafe24e9ab4cfea16da0ae6852e91637175db92b494baa83e8e658639ac0ff92aca34d23ca

test:
  secret_key_base: b4c289cd27bf0d49c9242ff2a1c76b922359ad95987301b710fd43d498e52151c4e41c716fcb323583756a42b8e3edd3363ee93c2559ea5cf71482e740103cc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
